version: '2'

services: 

  wifi: 
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
    cap_add: 
      - SYS_ADMIN
    volumes:      
      - ./src:/usr/src/app
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
  ui:
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: ./devops/docker/Dockerfile.ui
    volumes:
      - ./ui/src:/app/src
    ports:
      - '3000:3000'
    restart: always