version: '2'

services: 

  ui:
    build:
      target: ${APP_ENV}
      context: .
      dockerfile: ./devops/docker/Dockerfile.ui
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
        - APP_ENV=${APP_ENV}
    environment:
      APP_URL: ${APP_URL}
    volumes:
      - ./ui:/var/www/html
    ports:
      - '8080:8080'

  wific: 
    build:
      target: ${APP_ENV}
      context: .
      dockerfile: ./devops/docker/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    cap_add:
      - NET_ADMIN
    volumes:      
      - ./src:/usr/src/app
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    links:
      - ui
    restart: always