FROM node:20.5.0-bullseye-slim AS base

RUN apt-get -y update
RUN apt-get -y install git

WORKDIR /app

#Install App
COPY ui/public ./public
COPY ui/src ./src
COPY ui/eslint.config.js ./eslint.config.js
COPY ui/index.html ./index.html
COPY ui/package-lock.json ./package-lock.json
COPY ui/package.json ./package.json
COPY ui/tsconfig.app.json ./tsconfig.app.json
COPY ui/tsconfig.json ./tsconfig.json
COPY ui/tsconfig.node.json ./tsconfig.node.json
COPY ui/vite.config.ts ./vite.config.ts

RUN npm install

#Dev
FROM base AS dev

WORKDIR /app

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "dev" ]

#Builder
FROM base AS builder

RUN npm run build

#Prod
FROM nginx AS prod

COPY --from=builder /app/dist /usr/share/nginx/html